### ISSUE TITLE
Error running backup script

### ISSUE THREAD

**Issue by seeps001** [steadyequipment/node-firestore-backup#8] opened 2017-11-24 14:45 UTC
I get the following error having followed the instructions: 

"module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64-unknown/grpc_node.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/src/grpc_extension.js:30:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)"

**Comment by yoiang** [comment] 2017-11-30 16:44
Hey @seeps001 ! In the future please search if this issue has been reported before, this is a duplicate of #7 . If the suggested fix doesn't work feel free to post there!

**Closed by yoiang** 2017-11-30 16:44 UTC
