### ISSUE TITLE
Rename issue

### ISSUE THREAD

**Issue by Tulleb** [steadyequipment/node-firestore-backup#21] opened 2018-03-05 13:32 UTC
I have the following issue when trying to install `sudo npm install -g firestore-backup`.

> $ sudo npm install -g firestore-backup
> npm ERR! path /usr/local/lib/node_modules/firestore-backup/node_modules/grpc/node_modules/node-pre-gyp/node_modules/nopt
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/node_modules/node-pre-gyp/node_modules/nopt' -> '/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/node_modules/node-pre-gyp/node_modules/.nopt.DELETE'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/tulleb/.npm/_logs/2018-03-05T13_29_14_752Z-debug.log

My current npm version is:
> $ npm -v
> 5.6.0

Thanks for your work!

**Comment by jeremylorino** [comment] 2018-03-07 02:40
Could you upgrade your Node.js to latest LTS v8.9.x and try again please?

**Comment by Tulleb** [comment] 2018-03-07 09:35
Same thing (as root this time):

> root@Tulleb05:~# npm install -g firestore-backup
> npm ERR! path /usr/local/lib/node_modules/firestore-backup/node_modules/grpc/node_modules/node-pre-gyp/node_modules/nopt
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/node_modules/node-pre-gyp/node_modules/nopt' -> '/usr/local/lib/node_modules/firestore-backup/node_modules/grpc/node_modules/node-pre-gyp/node_modules/.nopt.DELETE'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-03-07T09_34_05_054Z-debug.log

-----------

> root@Tulleb05:~# node -v
> v8.9.4
> root@Tulleb05:~# npm -v
> 5.6.0

**Comment by jeremylorino** [comment] 2018-03-07 15:11
Let me spin up a fresh environment on cloud9 to test because "it works on my machine".

What's your environment stack?

**Comment by Tulleb** [comment] 2018-03-07 15:32
Ubuntu 16.04.3 LTS

I am not using anything else like docker... I don't know much about it 😕

**Comment by jeremylorino** [comment] 2018-03-07 15:35
No worries ;)

I just wanted to make sure I had a fresh environment to try and reproduce your issue.

**Comment by jeremylorino** [comment] 2018-03-07 16:05
@Tulleb real quick; if you run
```
npx firestore-backup
```
does it work?

**Comment by jeremylorino** [comment] 2018-03-07 16:09
@Tulleb here is the [c9 workspace](https://ide.c9.io/jlorino/node-firestore-backup) i just cloned to let us test

**Comment by Tulleb** [comment] 2018-03-07 16:15
@jeremylorino as soon as I found out to create an account over there... Worst website ever 😳

**Comment by jeremylorino** [comment] 2018-03-07 16:16
yaaaa sorry. you should be able to login with github

**Comment by Tulleb** [comment] 2018-03-07 16:16
Can't, I tried already :/
I'll looking into it. Thanks for the help once again @jeremylorino.

**Comment by Tulleb** [comment] 2018-03-07 16:19
It's actually working with 'npx' prefix 😍

**Comment by jeremylorino** [comment] 2018-03-07 16:27
it's a nice little command

[medium article](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b)
[npx git repo](https://github.com/zkat/npx)

**Comment by yoiang** [comment] 2018-03-20 19:23
It sounds like this is resolved so I'm closing it. Please say if it hasn't been!

**Closed by yoiang** 2018-03-20 19:23 UTC
